### ISSUE TITLE
Animations Programm raussuchen/testen

### ISSUE THREAD

**Issue by BlackWolf63** [Eldinox/Projekt_Neon#4]
Welches nehmen wir?
-Selim hatte schon welche mal rausgesucht
-in Unitiy kann man auch Animieren -> Waldemar weißt mehr

**Comment by HarryGuib** [comment]
**Spriter** : + ist gut und enthält schon manche Animation die wir brauchen können
                    - Ist Jetzt Kostenpflichtig für features die wir brauchen können
**DragonBone**: +Ist kostenlos
                            +Unkomplizierte Fläsche und intuitive Benutzung
                            - Unterstütz Grafik tablet zeichnung nicht
                            - nicht viele tutorials 
                            - manchmal crascht er
**Pencil2D** : +Kostenlos  
                       +Tutos vohanden
                       + Unterstüzt Grafik Tablett
                       - zu basic
**OpenToonz**: +Open Source 
                          + Man kann profesionnel ergebinisse erreichen
                          + Unterstüzt Grafik Tablett
                          +Tutos vohanden
                          + entwickelt bei Studi0 Ghibli ( Chihiros Reise ins Zauberland)
